set(_CATKIN_CURRENT_PACKAGE "ecl_console")
set(ecl_console_VERSION "0.61.6")
set(ecl_console_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(ecl_console_PACKAGE_FORMAT "1")
set(ecl_console_BUILD_DEPENDS "ecl_license" "ecl_build" "ecl_config")
set(ecl_console_BUILD_EXPORT_DEPENDS "ecl_license" "ecl_build" "ecl_config")
set(ecl_console_BUILDTOOL_DEPENDS "catkin")
set(ecl_console_BUILDTOOL_EXPORT_DEPENDS )
set(ecl_console_EXEC_DEPENDS "ecl_license" "ecl_build" "ecl_config")
set(ecl_console_RUN_DEPENDS "ecl_license" "ecl_build" "ecl_config")
set(ecl_console_TEST_DEPENDS )
set(ecl_console_DOC_DEPENDS )
set(ecl_console_DEPRECATED "")