# CMake generated Testfile for 
# Source directory: /home/korivi/model_car/ecl_lib/src/ecl_math/src/test
# Build directory: /home/korivi/model_car/ecl_lib/build_isolated/ecl_math/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ecl_math_gtest_ecl_test_constants "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_constants.xml" "--return-code" "/home/korivi/model_car/ecl_lib/devel_isolated/ecl_math/lib/ecl_math/ecl_test_constants --gtest_output=xml:/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_constants.xml")
add_test(_ctest_ecl_math_gtest_ecl_test_fuzzy "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_fuzzy.xml" "--return-code" "/home/korivi/model_car/ecl_lib/devel_isolated/ecl_math/lib/ecl_math/ecl_test_fuzzy --gtest_output=xml:/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_fuzzy.xml")
add_test(_ctest_ecl_math_gtest_ecl_test_norms "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_norms.xml" "--return-code" "/home/korivi/model_car/ecl_lib/devel_isolated/ecl_math/lib/ecl_math/ecl_test_norms --gtest_output=xml:/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_norms.xml")
add_test(_ctest_ecl_math_gtest_ecl_test_simple "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_simple.xml" "--return-code" "/home/korivi/model_car/ecl_lib/devel_isolated/ecl_math/lib/ecl_math/ecl_test_simple --gtest_output=xml:/home/korivi/model_car/ecl_lib/build_isolated/ecl_math/test_results/ecl_math/gtest-ecl_test_simple.xml")
