set(_CATKIN_CURRENT_PACKAGE "ecl_config")
set(ecl_config_VERSION "0.61.6")
set(ecl_config_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(ecl_config_PACKAGE_FORMAT "1")
set(ecl_config_BUILD_DEPENDS "ecl_build" "ecl_license")
set(ecl_config_BUILD_EXPORT_DEPENDS "ecl_license" "ecl_build")
set(ecl_config_BUILDTOOL_DEPENDS "catkin")
set(ecl_config_BUILDTOOL_EXPORT_DEPENDS )
set(ecl_config_EXEC_DEPENDS "ecl_license" "ecl_build")
set(ecl_config_RUN_DEPENDS "ecl_license" "ecl_build")
set(ecl_config_TEST_DEPENDS )
set(ecl_config_DOC_DEPENDS )
set(ecl_config_DEPRECATED "")