set(_CATKIN_CURRENT_PACKAGE "ecl_sigslots")
set(ecl_sigslots_VERSION "0.61.18")
set(ecl_sigslots_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(ecl_sigslots_PACKAGE_FORMAT "1")
set(ecl_sigslots_BUILD_DEPENDS "ecl_license" "ecl_config" "ecl_threads")
set(ecl_sigslots_BUILD_EXPORT_DEPENDS "ecl_license" "ecl_config" "ecl_threads")
set(ecl_sigslots_BUILDTOOL_DEPENDS "catkin")
set(ecl_sigslots_BUILDTOOL_EXPORT_DEPENDS )
set(ecl_sigslots_EXEC_DEPENDS "ecl_license" "ecl_config" "ecl_threads")
set(ecl_sigslots_RUN_DEPENDS "ecl_license" "ecl_config" "ecl_threads")
set(ecl_sigslots_TEST_DEPENDS )
set(ecl_sigslots_DOC_DEPENDS )
set(ecl_sigslots_DEPRECATED "")